import Head from 'next/head'
import Link from 'next/link'

import { NextPageWithLayout } from '~shared/next'
import { routesMap } from '~shared/routes'

const PremierePage: NextPageWithLayout = () => {
  return (
    <>
      {/* //TODO pass premiere title to the head */}
      <Head>
        <title>Премьера</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="w-full">
        premiere page
        <br />
        <Link href={routesMap.seance(25)}>
          <a>to seance page</a>
        </Link>
      </div>
    </>
  )
}

PremierePage.getLayout = (page) => page

export default PremierePage
