import {
  allSettled,
  attach,
  createEvent,
  fork,
  sample,
  serialize,
} from 'effector'
import { useMemo } from 'react'
import { useStoreMap } from 'effector-react'
import Head from 'next/head'
import type { GetServerSideProps } from 'next'

import { SeanceHeader } from '~widgets/seance-header'
import { SeanceLegend } from '~widgets/seance-legend'
import { SeanceFooter } from '~widgets/seance-footer'
import { HallScheme, hallSchemeModel } from '~widgets/hall-scheme'
import { selectSeatModel } from '~features/select-seat'
import { HallZoom } from '~features/hall-zoom'
import { cinema, CinemaScreen } from '~entities/cinema'
import { seance } from '~entities/seance'
import type { NextPageWithLayout } from '~shared/next'

const SeancePage: NextPageWithLayout = () => {
  return (
    <>
      <Helmet />
      <div className="w-full h-full flex flex-col relative">
        <SeanceHeader />
        <SeanceLegend />
        <CinemaScreen />
        <HallZoom />
        <HallScheme />
        <SeanceFooter />
      </div>
    </>
  )
}

const Helmet = () => {
  const { movieName, cinemaTitle } = useStoreMap(
    seance.model.$seance,
    (seance) => ({
      movieName: seance?.movie_title ?? null,
      cinemaTitle: seance?.cinema_title ?? null,
    })
  )

  const title = useMemo(() => {
    if (movieName && cinemaTitle) {
      return `Купить билет на фильм "${movieName}" в ${cinemaTitle}.`
    }
    return 'Купить билет на фильм в Ташкенте.'
  }, [movieName, cinemaTitle])

  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.svg" />
    </Head>
  )
}

const pageStarted = createEvent<{ id: number }>()

const fetchSeanceFx = attach({ effect: seance.model.fetchSeanceFx })

sample({
  clock: pageStarted,
  target: fetchSeanceFx,
})

export const getServerSideProps: GetServerSideProps = async (context) => {
  const scope = fork({
    values: [[selectSeatModel.$selectedSeatsIds, []]],
  })

  await allSettled(pageStarted, {
    scope,
    params: { id: +context.params!.sid! },
  })

  if (scope.getState(seance.model.$seance) === null) {
    return {
      notFound: true,
    }
  }

  const seats = scope.getState(seance.model.$seance)?.seance.seats ?? []

  const seatsX = seats.map((seat) => seat.x) ?? []
  const containerWidth = Math.max(...seatsX) + cinema.config.SEAT_WIDTH
  const containerHeight = seats[seats.length - 1].y + cinema.config.SEAT_WIDTH

  await allSettled(hallSchemeModel.heightAndWidthCalculated, {
    scope,
    params: { width: containerWidth, height: containerHeight },
  })

  return {
    props: {
      initialState: serialize(scope),
    },
  }
}

SeancePage.getLayout = (page) => page

export default SeancePage
