import Head from 'next/head'
import type { NextPage } from 'next'

const CinemasPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Кинотеатры</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="w-full">Cinemas page</div>
    </>
  )
}

export default CinemasPage
