import Head from 'next/head'
import Link from 'next/link'

const NotFoundPage = () => {
  return (
    <>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="w-full h-full flex flex-col items-center justify-center space-y-2">
        <h1>404</h1>
        <h5>Упс... Страница не найдена!</h5>
        <Link href="/">
          <a>Вернуться на главную</a>
        </Link>
      </div>
    </>
  )
}

export default NotFoundPage
