import type { NextPage } from 'next'
import Head from 'next/head'

import { PremieresSlider } from '~entities/seance'
import { PremiereDayPicker } from '~features/premiere-day-picker'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Премьеры недели, в кинотеатрах</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div className="w-full">
        <div className="flex flex-col space-y-5 w-full mb-10">
          <h1 className="text-2xl leading-7 font-extrabold pl-4">
            Премьеры недели
          </h1>
          <PremieresSlider />
        </div>
        <div className="flex flex-col w-full pl-4 space-y-4">
          <h1 className="text-2xl leading-7 font-extrabold pl-4">
            В кинотеатрах
          </h1>
          <div className="flex flex-col space-y-6 w-full">
            <PremiereDayPicker />
          </div>
        </div>
      </div>
    </>
  )
}

export default Home
